name: IT Mixed Coverage

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:

  it-action-coverage-classes:

    name: IT Mixed Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for fixtures
        uses: actions/checkout@v3

      - name: Assert coverage of azbazeliner.pricer package is above 85% and coverage of azbaseliner.util.collections.py is above 90%
        uses: zlatko-ms/pycovcheck@main
        with: 
          coveragefile: ./test/fixtures/unit/nose2/coverage1.xml
          packages:  azbaseliner.pricing:0.85
          classes: azbaseliner.util.collections.py:0.90

      - name: Assert coverage of all packages is above 80% while azbaseliner.util.collections.py is above 90% 
        uses: zlatko-ms/pycovcheck@main
        with: 
          coveragefile: ./test/fixtures/unit/nose2/coverage2.xml
          packages: :0.8
          classes: azbaseliner.util.collections.py:0.90